package com.freeman.mac.citytransporttimetable.database_model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.freeman.mac.citytransporttimetable.database_model.DbTrafficData;
import com.freeman.mac.citytransporttimetable.database_model.DbVehicleDescriptionItem;
import com.freeman.mac.citytransporttimetable.database_model.DbStreet;
import com.freeman.mac.citytransporttimetable.database_model.DbNextStreetInfo;
import com.freeman.mac.citytransporttimetable.database_model.DbTimePeriod;
import com.freeman.mac.citytransporttimetable.database_model.DbHourMapping;
import com.freeman.mac.citytransporttimetable.database_model.DbMinuteMapping;
import com.freeman.mac.citytransporttimetable.database_model.DbSign;

import com.freeman.mac.citytransporttimetable.database_model.DbTrafficDataDao;
import com.freeman.mac.citytransporttimetable.database_model.DbVehicleDescriptionItemDao;
import com.freeman.mac.citytransporttimetable.database_model.DbStreetDao;
import com.freeman.mac.citytransporttimetable.database_model.DbNextStreetInfoDao;
import com.freeman.mac.citytransporttimetable.database_model.DbTimePeriodDao;
import com.freeman.mac.citytransporttimetable.database_model.DbHourMappingDao;
import com.freeman.mac.citytransporttimetable.database_model.DbMinuteMappingDao;
import com.freeman.mac.citytransporttimetable.database_model.DbSignDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbTrafficDataDaoConfig;
    private final DaoConfig dbVehicleDescriptionItemDaoConfig;
    private final DaoConfig dbStreetDaoConfig;
    private final DaoConfig dbNextStreetInfoDaoConfig;
    private final DaoConfig dbTimePeriodDaoConfig;
    private final DaoConfig dbHourMappingDaoConfig;
    private final DaoConfig dbMinuteMappingDaoConfig;
    private final DaoConfig dbSignDaoConfig;

    private final DbTrafficDataDao dbTrafficDataDao;
    private final DbVehicleDescriptionItemDao dbVehicleDescriptionItemDao;
    private final DbStreetDao dbStreetDao;
    private final DbNextStreetInfoDao dbNextStreetInfoDao;
    private final DbTimePeriodDao dbTimePeriodDao;
    private final DbHourMappingDao dbHourMappingDao;
    private final DbMinuteMappingDao dbMinuteMappingDao;
    private final DbSignDao dbSignDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbTrafficDataDaoConfig = daoConfigMap.get(DbTrafficDataDao.class).clone();
        dbTrafficDataDaoConfig.initIdentityScope(type);

        dbVehicleDescriptionItemDaoConfig = daoConfigMap.get(DbVehicleDescriptionItemDao.class).clone();
        dbVehicleDescriptionItemDaoConfig.initIdentityScope(type);

        dbStreetDaoConfig = daoConfigMap.get(DbStreetDao.class).clone();
        dbStreetDaoConfig.initIdentityScope(type);

        dbNextStreetInfoDaoConfig = daoConfigMap.get(DbNextStreetInfoDao.class).clone();
        dbNextStreetInfoDaoConfig.initIdentityScope(type);

        dbTimePeriodDaoConfig = daoConfigMap.get(DbTimePeriodDao.class).clone();
        dbTimePeriodDaoConfig.initIdentityScope(type);

        dbHourMappingDaoConfig = daoConfigMap.get(DbHourMappingDao.class).clone();
        dbHourMappingDaoConfig.initIdentityScope(type);

        dbMinuteMappingDaoConfig = daoConfigMap.get(DbMinuteMappingDao.class).clone();
        dbMinuteMappingDaoConfig.initIdentityScope(type);

        dbSignDaoConfig = daoConfigMap.get(DbSignDao.class).clone();
        dbSignDaoConfig.initIdentityScope(type);

        dbTrafficDataDao = new DbTrafficDataDao(dbTrafficDataDaoConfig, this);
        dbVehicleDescriptionItemDao = new DbVehicleDescriptionItemDao(dbVehicleDescriptionItemDaoConfig, this);
        dbStreetDao = new DbStreetDao(dbStreetDaoConfig, this);
        dbNextStreetInfoDao = new DbNextStreetInfoDao(dbNextStreetInfoDaoConfig, this);
        dbTimePeriodDao = new DbTimePeriodDao(dbTimePeriodDaoConfig, this);
        dbHourMappingDao = new DbHourMappingDao(dbHourMappingDaoConfig, this);
        dbMinuteMappingDao = new DbMinuteMappingDao(dbMinuteMappingDaoConfig, this);
        dbSignDao = new DbSignDao(dbSignDaoConfig, this);

        registerDao(DbTrafficData.class, dbTrafficDataDao);
        registerDao(DbVehicleDescriptionItem.class, dbVehicleDescriptionItemDao);
        registerDao(DbStreet.class, dbStreetDao);
        registerDao(DbNextStreetInfo.class, dbNextStreetInfoDao);
        registerDao(DbTimePeriod.class, dbTimePeriodDao);
        registerDao(DbHourMapping.class, dbHourMappingDao);
        registerDao(DbMinuteMapping.class, dbMinuteMappingDao);
        registerDao(DbSign.class, dbSignDao);
    }
    
    public void clear() {
        dbTrafficDataDaoConfig.getIdentityScope().clear();
        dbVehicleDescriptionItemDaoConfig.getIdentityScope().clear();
        dbStreetDaoConfig.getIdentityScope().clear();
        dbNextStreetInfoDaoConfig.getIdentityScope().clear();
        dbTimePeriodDaoConfig.getIdentityScope().clear();
        dbHourMappingDaoConfig.getIdentityScope().clear();
        dbMinuteMappingDaoConfig.getIdentityScope().clear();
        dbSignDaoConfig.getIdentityScope().clear();
    }

    public DbTrafficDataDao getDbTrafficDataDao() {
        return dbTrafficDataDao;
    }

    public DbVehicleDescriptionItemDao getDbVehicleDescriptionItemDao() {
        return dbVehicleDescriptionItemDao;
    }

    public DbStreetDao getDbStreetDao() {
        return dbStreetDao;
    }

    public DbNextStreetInfoDao getDbNextStreetInfoDao() {
        return dbNextStreetInfoDao;
    }

    public DbTimePeriodDao getDbTimePeriodDao() {
        return dbTimePeriodDao;
    }

    public DbHourMappingDao getDbHourMappingDao() {
        return dbHourMappingDao;
    }

    public DbMinuteMappingDao getDbMinuteMappingDao() {
        return dbMinuteMappingDao;
    }

    public DbSignDao getDbSignDao() {
        return dbSignDao;
    }

}
