package com.freeman.mac.citytransporttimetable.database_model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.freeman.mac.citytransporttimetable.database_model.DbHourMapping;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_HOUR_MAPPING".
*/
public class DbHourMappingDao extends AbstractDao<DbHourMapping, Long> {

    public static final String TABLENAME = "DB_HOUR_MAPPING";

    /**
     * Properties of entity DbHourMapping.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hour = new Property(1, Integer.class, "Hour", false, "HOUR");
        public final static Property IdTimePeriod = new Property(2, Long.class, "IdTimePeriod", false, "ID_TIME_PERIOD");
    };

    private DaoSession daoSession;

    private Query<DbHourMapping> dbTimePeriod_DbHourMappingListQuery;

    public DbHourMappingDao(DaoConfig config) {
        super(config);
    }
    
    public DbHourMappingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_HOUR_MAPPING\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HOUR\" INTEGER," + // 1: Hour
                "\"ID_TIME_PERIOD\" INTEGER);"); // 2: IdTimePeriod
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DB_HOUR_MAPPING_ID_TIME_PERIOD ON DB_HOUR_MAPPING" +
                " (\"ID_TIME_PERIOD\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_HOUR_MAPPING\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbHourMapping entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer Hour = entity.getHour();
        if (Hour != null) {
            stmt.bindLong(2, Hour);
        }
 
        Long IdTimePeriod = entity.getIdTimePeriod();
        if (IdTimePeriod != null) {
            stmt.bindLong(3, IdTimePeriod);
        }
    }

    @Override
    protected void attachEntity(DbHourMapping entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbHourMapping readEntity(Cursor cursor, int offset) {
        DbHourMapping entity = new DbHourMapping( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // Hour
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // IdTimePeriod
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbHourMapping entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHour(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setIdTimePeriod(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbHourMapping entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbHourMapping entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbHourMappingList" to-many relationship of DbTimePeriod. */
    public List<DbHourMapping> _queryDbTimePeriod_DbHourMappingList(Long IdTimePeriod) {
        synchronized (this) {
            if (dbTimePeriod_DbHourMappingListQuery == null) {
                QueryBuilder<DbHourMapping> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdTimePeriod.eq(null));
                dbTimePeriod_DbHourMappingListQuery = queryBuilder.build();
            }
        }
        Query<DbHourMapping> query = dbTimePeriod_DbHourMappingListQuery.forCurrentThread();
        query.setParameter(0, IdTimePeriod);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbTimePeriodDao().getAllColumns());
            builder.append(" FROM DB_HOUR_MAPPING T");
            builder.append(" LEFT JOIN DB_TIME_PERIOD T0 ON T.\"ID_TIME_PERIOD\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbHourMapping loadCurrentDeep(Cursor cursor, boolean lock) {
        DbHourMapping entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbTimePeriod dbTimePeriod = loadCurrentOther(daoSession.getDbTimePeriodDao(), cursor, offset);
        entity.setDbTimePeriod(dbTimePeriod);

        return entity;    
    }

    public DbHourMapping loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbHourMapping> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbHourMapping> list = new ArrayList<DbHourMapping>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbHourMapping> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbHourMapping> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
