package com.freeman.mac.citytransporttimetable.database_model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.freeman.mac.citytransporttimetable.database_model.DbNextStreetInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_NEXT_STREET_INFO".
*/
public class DbNextStreetInfoDao extends AbstractDao<DbNextStreetInfo, Long> {

    public static final String TABLENAME = "DB_NEXT_STREET_INFO";

    /**
     * Properties of entity DbNextStreetInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "Name", false, "NAME");
        public final static Property Duration = new Property(2, Integer.class, "Duration", false, "DURATION");
        public final static Property IdStreet = new Property(3, Long.class, "IdStreet", false, "ID_STREET");
    };

    private DaoSession daoSession;

    private Query<DbNextStreetInfo> dbStreet_DbNextStreetInfoListQuery;

    public DbNextStreetInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DbNextStreetInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_NEXT_STREET_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: Name
                "\"DURATION\" INTEGER," + // 2: Duration
                "\"ID_STREET\" INTEGER);"); // 3: IdStreet
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DB_NEXT_STREET_INFO_ID_STREET ON DB_NEXT_STREET_INFO" +
                " (\"ID_STREET\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_NEXT_STREET_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbNextStreetInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(2, Name);
        }
 
        Integer Duration = entity.getDuration();
        if (Duration != null) {
            stmt.bindLong(3, Duration);
        }
 
        Long IdStreet = entity.getIdStreet();
        if (IdStreet != null) {
            stmt.bindLong(4, IdStreet);
        }
    }

    @Override
    protected void attachEntity(DbNextStreetInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbNextStreetInfo readEntity(Cursor cursor, int offset) {
        DbNextStreetInfo entity = new DbNextStreetInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // Duration
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // IdStreet
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbNextStreetInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDuration(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setIdStreet(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbNextStreetInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbNextStreetInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbNextStreetInfoList" to-many relationship of DbStreet. */
    public List<DbNextStreetInfo> _queryDbStreet_DbNextStreetInfoList(Long IdStreet) {
        synchronized (this) {
            if (dbStreet_DbNextStreetInfoListQuery == null) {
                QueryBuilder<DbNextStreetInfo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdStreet.eq(null));
                dbStreet_DbNextStreetInfoListQuery = queryBuilder.build();
            }
        }
        Query<DbNextStreetInfo> query = dbStreet_DbNextStreetInfoListQuery.forCurrentThread();
        query.setParameter(0, IdStreet);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbStreetDao().getAllColumns());
            builder.append(" FROM DB_NEXT_STREET_INFO T");
            builder.append(" LEFT JOIN DB_STREET T0 ON T.\"ID_STREET\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbNextStreetInfo loadCurrentDeep(Cursor cursor, boolean lock) {
        DbNextStreetInfo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbStreet dbStreet = loadCurrentOther(daoSession.getDbStreetDao(), cursor, offset);
        entity.setDbStreet(dbStreet);

        return entity;    
    }

    public DbNextStreetInfo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbNextStreetInfo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbNextStreetInfo> list = new ArrayList<DbNextStreetInfo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbNextStreetInfo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbNextStreetInfo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
