package com.freeman.mac.citytransporttimetable.database_model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.freeman.mac.citytransporttimetable.database_model.DbSign;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_SIGN".
*/
public class DbSignDao extends AbstractDao<DbSign, Long> {

    public static final String TABLENAME = "DB_SIGN";

    /**
     * Properties of entity DbSign.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Value = new Property(1, String.class, "Value", false, "VALUE");
        public final static Property IdMinuteMapping = new Property(2, Long.class, "IdMinuteMapping", false, "ID_MINUTE_MAPPING");
    };

    private DaoSession daoSession;

    private Query<DbSign> dbMinuteMapping_DbSignListQuery;

    public DbSignDao(DaoConfig config) {
        super(config);
    }
    
    public DbSignDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_SIGN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VALUE\" TEXT," + // 1: Value
                "\"ID_MINUTE_MAPPING\" INTEGER);"); // 2: IdMinuteMapping
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DB_SIGN_ID_MINUTE_MAPPING ON DB_SIGN" +
                " (\"ID_MINUTE_MAPPING\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_SIGN\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbSign entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Value = entity.getValue();
        if (Value != null) {
            stmt.bindString(2, Value);
        }
 
        Long IdMinuteMapping = entity.getIdMinuteMapping();
        if (IdMinuteMapping != null) {
            stmt.bindLong(3, IdMinuteMapping);
        }
    }

    @Override
    protected void attachEntity(DbSign entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbSign readEntity(Cursor cursor, int offset) {
        DbSign entity = new DbSign( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Value
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // IdMinuteMapping
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbSign entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIdMinuteMapping(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbSign entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbSign entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbSignList" to-many relationship of DbMinuteMapping. */
    public List<DbSign> _queryDbMinuteMapping_DbSignList(Long IdMinuteMapping) {
        synchronized (this) {
            if (dbMinuteMapping_DbSignListQuery == null) {
                QueryBuilder<DbSign> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdMinuteMapping.eq(null));
                dbMinuteMapping_DbSignListQuery = queryBuilder.build();
            }
        }
        Query<DbSign> query = dbMinuteMapping_DbSignListQuery.forCurrentThread();
        query.setParameter(0, IdMinuteMapping);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbMinuteMappingDao().getAllColumns());
            builder.append(" FROM DB_SIGN T");
            builder.append(" LEFT JOIN DB_MINUTE_MAPPING T0 ON T.\"ID_MINUTE_MAPPING\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbSign loadCurrentDeep(Cursor cursor, boolean lock) {
        DbSign entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbMinuteMapping dbMinuteMapping = loadCurrentOther(daoSession.getDbMinuteMappingDao(), cursor, offset);
        entity.setDbMinuteMapping(dbMinuteMapping);

        return entity;    
    }

    public DbSign loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbSign> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbSign> list = new ArrayList<DbSign>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbSign> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbSign> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
