package com.freeman.mac.citytransporttimetable.database_model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.freeman.mac.citytransporttimetable.database_model.DbStreet;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_STREET".
*/
public class DbStreetDao extends AbstractDao<DbStreet, Long> {

    public static final String TABLENAME = "DB_STREET";

    /**
     * Properties of entity DbStreet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DirectionType = new Property(1, Integer.class, "DirectionType", false, "DIRECTION_TYPE");
        public final static Property Name = new Property(2, String.class, "Name", false, "NAME");
        public final static Property RequestStop = new Property(3, Boolean.class, "RequestStop", false, "REQUEST_STOP");
        public final static Property CircleDirectionName = new Property(4, String.class, "CircleDirectionName", false, "CIRCLE_DIRECTION_NAME");
        public final static Property IdTrafficData = new Property(5, Long.class, "IdTrafficData", false, "ID_TRAFFIC_DATA");
    };

    private DaoSession daoSession;

    private Query<DbStreet> dbTrafficData_DbStreetListQuery;

    public DbStreetDao(DaoConfig config) {
        super(config);
    }
    
    public DbStreetDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_STREET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DIRECTION_TYPE\" INTEGER," + // 1: DirectionType
                "\"NAME\" TEXT," + // 2: Name
                "\"REQUEST_STOP\" INTEGER," + // 3: RequestStop
                "\"CIRCLE_DIRECTION_NAME\" TEXT," + // 4: CircleDirectionName
                "\"ID_TRAFFIC_DATA\" INTEGER);"); // 5: IdTrafficData
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DB_STREET_ID_TRAFFIC_DATA ON DB_STREET" +
                " (\"ID_TRAFFIC_DATA\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_STREET\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbStreet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer DirectionType = entity.getDirectionType();
        if (DirectionType != null) {
            stmt.bindLong(2, DirectionType);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(3, Name);
        }
 
        Boolean RequestStop = entity.getRequestStop();
        if (RequestStop != null) {
            stmt.bindLong(4, RequestStop ? 1L: 0L);
        }
 
        String CircleDirectionName = entity.getCircleDirectionName();
        if (CircleDirectionName != null) {
            stmt.bindString(5, CircleDirectionName);
        }
 
        Long IdTrafficData = entity.getIdTrafficData();
        if (IdTrafficData != null) {
            stmt.bindLong(6, IdTrafficData);
        }
    }

    @Override
    protected void attachEntity(DbStreet entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbStreet readEntity(Cursor cursor, int offset) {
        DbStreet entity = new DbStreet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // DirectionType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Name
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // RequestStop
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // CircleDirectionName
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // IdTrafficData
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbStreet entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDirectionType(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRequestStop(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setCircleDirectionName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIdTrafficData(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbStreet entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbStreet entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbStreetList" to-many relationship of DbTrafficData. */
    public List<DbStreet> _queryDbTrafficData_DbStreetList(Long IdTrafficData) {
        synchronized (this) {
            if (dbTrafficData_DbStreetListQuery == null) {
                QueryBuilder<DbStreet> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdTrafficData.eq(null));
                dbTrafficData_DbStreetListQuery = queryBuilder.build();
            }
        }
        Query<DbStreet> query = dbTrafficData_DbStreetListQuery.forCurrentThread();
        query.setParameter(0, IdTrafficData);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbTrafficDataDao().getAllColumns());
            builder.append(" FROM DB_STREET T");
            builder.append(" LEFT JOIN DB_TRAFFIC_DATA T0 ON T.\"ID_TRAFFIC_DATA\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbStreet loadCurrentDeep(Cursor cursor, boolean lock) {
        DbStreet entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbTrafficData dbTrafficData = loadCurrentOther(daoSession.getDbTrafficDataDao(), cursor, offset);
        entity.setDbTrafficData(dbTrafficData);

        return entity;    
    }

    public DbStreet loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbStreet> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbStreet> list = new ArrayList<DbStreet>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbStreet> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbStreet> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
