package com.freeman.mac.citytransporttimetable.database_model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.freeman.mac.citytransporttimetable.database_model.DbVehicleDescriptionItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_VEHICLE_DESCRIPTION_ITEM".
*/
public class DbVehicleDescriptionItemDao extends AbstractDao<DbVehicleDescriptionItem, Long> {

    public static final String TABLENAME = "DB_VEHICLE_DESCRIPTION_ITEM";

    /**
     * Properties of entity DbVehicleDescriptionItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Text = new Property(1, String.class, "Text", false, "TEXT");
        public final static Property Sign = new Property(2, String.class, "Sign", false, "SIGN");
        public final static Property IdTrafficData = new Property(3, Long.class, "IdTrafficData", false, "ID_TRAFFIC_DATA");
    };

    private DaoSession daoSession;

    private Query<DbVehicleDescriptionItem> dbTrafficData_DbVehicleDescriptionItemListQuery;

    public DbVehicleDescriptionItemDao(DaoConfig config) {
        super(config);
    }
    
    public DbVehicleDescriptionItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_VEHICLE_DESCRIPTION_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TEXT\" TEXT," + // 1: Text
                "\"SIGN\" TEXT," + // 2: Sign
                "\"ID_TRAFFIC_DATA\" INTEGER);"); // 3: IdTrafficData
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_DB_VEHICLE_DESCRIPTION_ITEM_ID_TRAFFIC_DATA ON DB_VEHICLE_DESCRIPTION_ITEM" +
                " (\"ID_TRAFFIC_DATA\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_VEHICLE_DESCRIPTION_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbVehicleDescriptionItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Text = entity.getText();
        if (Text != null) {
            stmt.bindString(2, Text);
        }
 
        String Sign = entity.getSign();
        if (Sign != null) {
            stmt.bindString(3, Sign);
        }
 
        Long IdTrafficData = entity.getIdTrafficData();
        if (IdTrafficData != null) {
            stmt.bindLong(4, IdTrafficData);
        }
    }

    @Override
    protected void attachEntity(DbVehicleDescriptionItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbVehicleDescriptionItem readEntity(Cursor cursor, int offset) {
        DbVehicleDescriptionItem entity = new DbVehicleDescriptionItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Text
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Sign
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // IdTrafficData
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbVehicleDescriptionItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setText(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSign(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdTrafficData(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbVehicleDescriptionItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbVehicleDescriptionItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbVehicleDescriptionItemList" to-many relationship of DbTrafficData. */
    public List<DbVehicleDescriptionItem> _queryDbTrafficData_DbVehicleDescriptionItemList(Long IdTrafficData) {
        synchronized (this) {
            if (dbTrafficData_DbVehicleDescriptionItemListQuery == null) {
                QueryBuilder<DbVehicleDescriptionItem> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdTrafficData.eq(null));
                dbTrafficData_DbVehicleDescriptionItemListQuery = queryBuilder.build();
            }
        }
        Query<DbVehicleDescriptionItem> query = dbTrafficData_DbVehicleDescriptionItemListQuery.forCurrentThread();
        query.setParameter(0, IdTrafficData);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbTrafficDataDao().getAllColumns());
            builder.append(" FROM DB_VEHICLE_DESCRIPTION_ITEM T");
            builder.append(" LEFT JOIN DB_TRAFFIC_DATA T0 ON T.\"ID_TRAFFIC_DATA\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbVehicleDescriptionItem loadCurrentDeep(Cursor cursor, boolean lock) {
        DbVehicleDescriptionItem entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbTrafficData dbTrafficData = loadCurrentOther(daoSession.getDbTrafficDataDao(), cursor, offset);
        entity.setDbTrafficData(dbTrafficData);

        return entity;    
    }

    public DbVehicleDescriptionItem loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbVehicleDescriptionItem> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbVehicleDescriptionItem> list = new ArrayList<DbVehicleDescriptionItem>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbVehicleDescriptionItem> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbVehicleDescriptionItem> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
